theme: "jekyll-theme-cayman"

lang: "de-DE"
author: "Philipp Kraus"
title: "Informatikwerkstatt"
description: "Mobile App Entwicklung mit Android"

license:
    text: "Creative Commons Lizenzvertrag"
    link: "http://creativecommons.org/licenses/by-sa/4.0/"
    image: "https://i.creativecommons.org/l/by-sa/4.0/80x15.png"